### ISSUE TITLE
Game crashes when harp icon is clicked

### ISSUE THREAD

**Issue by daichungus** [SomeUnusualGames/Flag-Wars#3]
The game immediately crashes after clicking the harp icon in the upper right corner. In addition, the music is set to zero by default. 

Users should at least have the option of toggling the music on and off without the game crashing. 

`This.MusicIcon = LoadTexture("assets/graphics/harp.png")`
    `This.BackgroundMusic = LoadMusicStream("assets/music/Battle for Extranite.mp3")`
    `This.MusicVolume = 0.0`
    `SetMusicVolume(This.BackgroundMusic, This.MusicVolume)`
    `PlayMusicStream(This.BackgroundMusic)`

**Comment by SomeUnusualGames** [comment]
Turns out, even though the `music` folder exists in the itch.io release, I accidentally deleted it when compiling the game. I believe that's why the executable failed to find it and crashed.

Recompiled with the music folder and updated the [itch.io release](https://someunusualgames.itch.io/flag-wars-argentina-vs-uruguay), it shouldn't crash anymore.

**Comment by daichungus** [comment]
Yup, it doesn't crash anymore. Thanks for fixing it!
